#!/usr/bin/env bash
# spec-divergence-poc.sh — PROOF OF CONCEPT (not wired into anything). Computes a DIVERGENCE SCORE from
# N independently-generated task interpretations, to test ONE claim:
#
#   "A vague/under-specified prompt yields HIGH divergence across independent interpretations; a
#    well-specified prompt yields LOW divergence. The score is COMPUTED from the interpretations,
#    not self-reported by the agent."
#
# ┌──────────────────────────────────────────────────────────────────────────────────────────────┐
# │ POC ONLY. NOT wired into scaffold/migrate, NOT a Phase 0, NOT a gate. This proves-or-falsifies   │
# │ the core signal the Issues-1+2+3 subsystem would rest on, before any full build.                │
# └──────────────────────────────────────────────────────────────────────────────────────────────┘
#
# THE CRITICAL PROPERTY (mechanical, not self-assessed): the interpretations are generated by INDEPENDENT
# blind agents (each sees only the prompt + a fixed schema; none is told the hypothesis or whether the
# prompt is "supposed to be" vague). This script does NOT ask any agent "how confident are you" — it reads
# the structured interpretations and COMPUTES disagreement. The score is a function of the interpretation
# set, full stop.
#
# INPUT: a JSON file: {"interpretations": [ {scope_one_line, in_scope[], comparison_surfaces[],
#        key_behaviors[], assumptions_i_had_to_make[]}, ... ]}  (>= 2 interpretations).
#
# DIVERGENCE MODEL (deterministic, computed from the set):
#   For each SET-VALUED axis (comparison_surfaces, in_scope, key_behaviors), normalize each item
#   (lowercase, strip punctuation, collapse whitespace, take a content token-set) and compute the mean
#   pairwise Jaccard DISTANCE (1 - |A∩B|/|A∪B|) across all interpretation pairs on that axis. High distance
#   = the interpreters disagreed on that axis. Also report mean assumptions-count (more forced assumptions
#   = more gaps the request left open). The overall DIVERGENCE = mean of the per-axis mean pairwise
#   distances, in [0,1]. Higher = more under-specified.
#
# Usage:
#   bash lib/spec-divergence-poc.sh <interpretations.json>           # prints score + per-axis breakdown
#   bash lib/spec-divergence-poc.sh <interpretations.json> --score   # prints ONLY the overall score (0..1)
#
# Exit: 0 = scored OK · 2 = usage / parse error / fewer than 2 interpretations.
# NOTE: this POC deliberately does NOT exit-2-on-"too vague" — it is a MEASUREMENT tool, not a gate. The
# gate decision (threshold → block) is explicitly out of scope for the POC.

set -uo pipefail

IN="${1:-}"
MODE="${2:-full}"
if [ -z "$IN" ]; then
  echo "Usage: $0 <interpretations.json> [--score]" >&2
  exit 2
fi
[ -f "$IN" ] || { echo "ERROR: interpretations file not found: $IN" >&2; exit 2; }

PYTHON_CMD=""
for c in python3 python; do
  if command -v "$c" &>/dev/null && "$c" -c "pass" &>/dev/null 2>&1; then PYTHON_CMD="$c"; break; fi
done
[ -n "$PYTHON_CMD" ] || { echo "ERROR: spec-divergence-poc needs a working python interpreter." >&2; exit 2; }

IN="$IN" MODE="$MODE" "$PYTHON_CMD" - "$IN" <<'PYEOF'
import json, os, re, sys, itertools

path = sys.argv[1]
mode = os.environ.get("MODE", "full")

try:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
except Exception as e:
    print(f"ERROR: could not parse JSON: {e}", file=sys.stderr); sys.exit(2)

interps = data.get("interpretations", [])
if not isinstance(interps, list) or len(interps) < 2:
    print("ERROR: need >= 2 interpretations to measure divergence", file=sys.stderr); sys.exit(2)

SET_AXES = ["comparison_surfaces", "in_scope", "key_behaviors"]

# Light stopword list so trivial words don't inflate overlap; the signal is content tokens.
STOP = set("a an the of to and or for with on in into via using use that this is are be as it its by "
           "add adds added implement implemented build building create creates new service api endpoint "
           "from path data".split())

def tokens(s):
    """Normalize a free-text item into a content-token SET: lowercase, strip punctuation, drop stopwords."""
    s = s.lower()
    s = re.sub(r'[^a-z0-9_ ]+', ' ', s)
    toks = [t for t in s.split() if t and t not in STOP and len(t) > 1]
    return set(toks)

def item_set(items):
    """Union the token-sets of every item in one interpretation's axis list -> one bag of content tokens."""
    bag = set()
    for it in (items or []):
        if isinstance(it, str):
            bag |= tokens(it)
    return bag

def jaccard_distance(a, b):
    if not a and not b:
        return 0.0          # both empty -> they agree (vacuously)
    if not a or not b:
        return 1.0          # one empty, one not -> total disagreement
    inter = len(a & b); union = len(a | b)
    return 1.0 - (inter / union)

def mean_pairwise_distance(token_sets):
    pairs = list(itertools.combinations(range(len(token_sets)), 2))
    if not pairs:
        return 0.0
    return sum(jaccard_distance(token_sets[i], token_sets[j]) for i, j in pairs) / len(pairs)

per_axis = {}
for axis in SET_AXES:
    token_sets = [item_set(intp.get(axis, [])) for intp in interps]
    per_axis[axis] = mean_pairwise_distance(token_sets)

# scope_one_line: token-set distance too (a single string per interpretation).
scope_sets = [tokens(intp.get("scope_one_line", "") or "") for intp in interps]
per_axis["scope_one_line"] = mean_pairwise_distance(scope_sets)

# Forced-assumptions: mean count across interpretations (a gap signal, reported but NOT folded into the
# divergence number — kept separate so the headline score is purely interpretation-disagreement).
assum_counts = [len(intp.get("assumptions_i_had_to_make", []) or []) for intp in interps]
mean_assumptions = sum(assum_counts) / len(assum_counts) if assum_counts else 0.0

scored_axes = SET_AXES + ["scope_one_line"]
overall = sum(per_axis[a] for a in scored_axes) / len(scored_axes)

if mode == "--score":
    print(f"{overall:.4f}")
    sys.exit(0)

print(f"interpretations: {len(interps)}")
print(f"OVERALL DIVERGENCE: {overall:.4f}   (0 = identical readings, 1 = total disagreement)")
print("per-axis mean pairwise Jaccard distance:")
for a in scored_axes:
    print(f"  {a:24s} {per_axis[a]:.4f}")
print(f"mean forced-assumptions per interpretation: {mean_assumptions:.2f}  (reported, NOT in the score)")
sys.exit(0)
PYEOF
RC=$?
exit $RC
